version: '3.0'

services:
  rust-dev-env:
    build: .
    container_name: rust-dev-env
    volumes:
      - ./:/home/trash-alarm
      - /dev/sda1:/dev/sda1
    working_dir: /home/trash-alarm
    command: tail -f /dev/null