version: '3.0'

services:
  trash-alarm-dev-env:
    build: .
    container_name: trash-alarm-dev-env
    volumes:
      - ./:/home/trash-alarm
      - /dev:/dev
    privileged: true # To have access to /dev of host machine to mount the pico
    working_dir: /home/trash-alarm
    command: sudo /usr/bin/supervisord # Starts the ssh server
    ports:
      - 2222:22
