[package]
name = "led"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp-pico = "0.5"
cortex-m = "0.7"
embedded-hal = { version = "0.2.5", features = ["unproven"] }