name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  building:
    name: Building
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
        os:
          # Check compilation works on common OSes
          # (i.e. no path issues)
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test