name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    name: Testing
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test